import { Reel, type ReelSlide } from '../components/Reel';

const homeSlides: ReelSlide[] = [
  { id: 1, title: "Tejas M", subtitle: "Digital Craftsman", category: "Identity", meta1: "2026", meta2: "SolidJS · Cybersecurity", image: "/images/image-1121789181016734.avif", description: "Architecting the future of the web with high-performance frameworks and a focus on security-first design." },
  { id: 2, title: "SolidJS Mastery", subtitle: "Reactive Engineering", category: "Tech Stack", meta1: "Vite", meta2: "Performance · UI", image: "/images/image-1121790164349969.avif", description: "Building ultra-fast, fine-grained reactive applications using SolidJS and SolidStart." },
  { id: 3, title: "Cybersecurity", subtitle: "Digital Fortress", category: "Expertise", meta1: "Infosec", meta2: "Protection · Auditing", image: "/images/image-1121795404349445.avif", description: "Developing robust defensive architectures and conducting deep-dive security audits." },
  { id: 4, title: "Cryptography", subtitle: "Privacy & Encryption", category: "Specialization", meta1: "Math", meta2: "Security · Trust", image: "/images/image-1121793034349682.avif", description: "Implementing complex cryptographic protocols to ensure absolute user privacy." },
  { id: 5, title: "Cinematic Motion", subtitle: "UI/UX Design", category: "Aesthetic", meta1: "GSAP", meta2: "Motion · Optics", image: "/images/image-1121796034349382.avif", description: "Crafting fluid, high-end interfaces that prioritize micro-interactions and optical excellence." },
  { id: 6, title: "High Performance", subtitle: "Edge Computing", category: "Optimization", meta1: "SSR", meta2: "Speed · Scaling", image: "/images/image-1121796544349331.avif", description: "Pushing the boundaries of speed with server-side rendering and distributed edge infrastructure." },
  { id: 7, title: "System Design", subtitle: "Architecture", category: "Backend", meta1: "NodeJS", meta2: "Scalable · Robust", image: "/images/image-1121789187683400.avif", description: "Designing distributed systems that handle high traffic with zero downtime." },
  { id: 8, title: "Authentication", subtitle: "Public Key", category: "Security", meta1: "Passkeys", meta2: "WebAuthn · Bio", image: "/images/image-1121789191016733.avif", description: "Eliminating passwords with modern biometric and hardware-backed authentication flows." },
  { id: 9, title: "State Machines", subtitle: "Deterministic UI", category: "Logic", meta1: "XState", meta2: "Complex · Flow", image: "/images/image-1121796031016049.avif", description: "Using finite state machines to govern complex user interactions with mathematical certainty." },
  { id: 10, title: "Cloud Native", subtitle: "Infrastructure", category: "DevOps", meta1: "Docker", meta2: "K8s · Deploy", image: "/images/image-1121796551015997.avif", description: "Containerizing applications for seamless deployment across any cloud environment." },
  { id: 11, title: "Data Privacy", subtitle: "Zero Knowledge", category: "Cryptography", meta1: "ZK-Proofs", meta2: "Private · Secure", image: "/images/image-1121794107682908.avif", description: "Enabling verifiable privacy with advanced zero-knowledge mathematical proofs." },
  { id: 12, title: "Visual Physics", subtitle: "Creative Code", category: "Interface", meta1: "Canvas", meta2: "Fluid · Dynamic", image: "/images/image-1121793041016348.avif", description: "Simulating physical properties like inertia and friction within the browser interface." },
  { id: 13, title: "Threat Analysis", subtitle: "Risk Management", category: "Security", meta1: "Auditing", meta2: "Detection · Mitigate", image: "/images/image-1121790171016635.avif", description: "Proactively identifying vulnerabilities before they can be exploited by malicious actors." },
  { id: 14, title: "Vite Ecosystem", subtitle: "Build Tools", category: "Development", meta1: "Tooling", meta2: "DX · Speed", image: "/images/image-1121794114349574.avif", description: "Leveraging lightning-fast build cycles to maintain high momentum during development." },
  { id: 15, title: "Glassmorphism", subtitle: "Optical UI", category: "Design", meta1: "Refraction", meta2: "Layered · Depth", image: "/images/image-1121794117682907.avif", description: "Creating depth and hierarchy through translucent, light-bending interface elements." },
  { id: 16, title: "Reactivity", subtitle: "Fine Grained", category: "SolidJS", meta1: "No VDOM", meta2: "Direct · Fast", image: "/images/image-1121794571016195.avif", description: "Bypassing the virtual DOM for direct, surgical updates to the browser's UI." },
  { id: 17, title: "API Design", subtitle: "Rest & GraphQL", category: "Backend", meta1: "Schemas", meta2: "Type Safe · Auto", image: "/images/image-1121793037683015.avif", description: "Building self-documenting APIs that bridge the gap between frontend and backend seamlessly." },
  { id: 18, title: "Auditing", subtitle: "Smart Contracts", category: "Blockchain", meta1: "Solidity", meta2: "DeFi · Safe", image: "/images/image-1121791417683177.avif", description: "Securing decentralized finance protocols through rigorous code analysis and testing." },
  { id: 19, title: "Motion Lab", subtitle: "Animation", category: "GSAP", meta1: "Physics", meta2: "Timeline · Easing", image: "/images/image-1121793031016349.avif", description: "Choreographing complex multi-step animations with frame-perfect precision." },
  { id: 20, title: "Network Intel", subtitle: "Traffic Analysis", category: "Security", meta1: "PCAP", meta2: "Analysis · Wire", image: "/images/image-1121794111016241.avif", description: "Monitoring network packets in real-time to identify anomalous communication patterns." },
  { id: 21, title: "UI Components", subtitle: "Design System", category: "Atomic", meta1: "Reusable", meta2: "Pattern · Scale", image: "/images/image-1121796024349383.avif", description: "Maintaining consistency across large-scale applications with a modular component library." },
  { id: 22, title: "User Experience", subtitle: "Accessibility", category: "Inclusive", meta1: "WCAG", meta2: "Screen · Key", image: "/images/image-1121796027682716.avif", description: "Ensuring that high-end digital experiences remain accessible to everyone." },
  { id: 23, title: "Quantum Sim", subtitle: "Educational", category: "Research", meta1: "Physics", meta2: "Compute · Logic", image: "/images/image-1121796547682664.avif", description: "Visualizing the foundational principles of quantum computing for academic exploration." },
  { id: 24, title: "Navigation", subtitle: "Liquid Nav", category: "Experience", meta1: "Flow", meta2: "Optical · Glass", image: "/images/image-1121796554349330.avif", description: "Innovating how users move through digital spaces with refractive menu systems." },
  { id: 25, title: "The Award Vision", subtitle: "Future Tech", category: "Philosophy", meta1: "2026", meta2: "Innovation · UX", image: "/images/image-1121789184350067.avif", description: "Creating the next generation of award-winning digital artifacts." }
];

export function Home() {
  return <Reel slides={homeSlides} />;
}
